CREATE DATABASE LINK CB.DBL CONNECT TO CB IDENTIFIED BY CB USING 'CB';


CREATE OR REPLACE TRIGGER COPIECOTESAVIS
BEFORE INSERT OR UPDATE ON EVALUATION
FOR EACH ROW
BEGIN
	:NEW.TOKEN := 'OK';

	IF (INSERTING) THEN
		INSERT INTO EVALUATION@CB.DBL (IDFILM, LOGIN, COTE, AVIS, DATEEVAL, TOKEN)
		VALUES (:NEW.IDFILM, :NEW.LOGIN, :NEW.COTE, :NEW.AVIS, :NEW.DATEEVAL, :NEW.TOKEN);
	END IF;

	IF (UPDATING) THEN
		UPDATE EVALUATION@CB.DBL
		SET	COTE = :NEW.COTE,
			AVIS = :NEW.AVIS,
			DATEEVAL = :NEW.DATEEVAL,
			TOKEN = :NEW.TOKEN
		WHERE	IDFILM = :NEW.IDFILM AND LOGIN = :NEW.LOGIN;
	END IF;

EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE = -02291 THEN :NEW.TOKEN := 'KO';
		ELSE RAISE;
		END IF;
END;
/
