CREATE DATABASE LINK CBB.DBL CONNECT TO CBB IDENTIFIED BY CBB USING 'CBB';


CREATE OR REPLACE TRIGGER COPIECOTESAVIS
BEFORE INSERT OR UPDATE ON EVALUATION
FOR EACH ROW
BEGIN
	DBMS_OUTPUT.PUT_LINE('DECLENCHEUR CB');
	DBMS_OUTPUT.PUT_LINE('Token cb 1 : ' || :NEW.TOKEN);
	:NEW.TOKEN := 'OK';
	DBMS_OUTPUT.PUT_LINE('Token cb 2 : ' || :NEW.TOKEN);

		IF (INSERTING) THEN
			DBMS_OUTPUT.PUT_LINE('insert cb');
			DBMS_OUTPUT.PUT_LINE('Token cb 3 : ' || :NEW.TOKEN);
			INSERT INTO EVALUATION@CBB.DBL (IDFILM, LOGIN, COTE, AVIS, DATEEVAL, TOKEN)
			VALUES (:NEW.IDFILM, :NEW.LOGIN, :NEW.COTE, :NEW.AVIS, :NEW.DATEEVAL, :NEW.TOKEN);
			DBMS_OUTPUT.PUT_LINE('Token cb 4 : ' || :NEW.TOKEN);
		END IF;

		IF (UPDATING) THEN
			UPDATE EVALUATION@CBB.DBL
			SET	COTE = :NEW.COTE,
				AVIS = :NEW.AVIS,
				DATEEVAL = :NEW.DATEEVAL,
				TOKEN = :NEW.TOKEN
			WHERE	IDFILM = :NEW.IDFILM AND LOGIN = :NEW.LOGIN;
		END IF;

EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('except cb');
		DBMS_OUTPUT.PUT_LINE('Token cb 5 : ' || :NEW.TOKEN);
		DBMS_OUTPUT.PUT_LINE(SQLCODE);
		IF SQLCODE = -02291 THEN :NEW.TOKEN := 'KO';
		DBMS_OUTPUT.PUT_LINE('Token cb 6 : ' || :NEW.TOKEN);
		ELSE RAISE;
		END IF;
END;
/


INSERT INTO EVALUATION VALUES (10, 'DDD', 7, 'Coucou',  to_timestamp('23/09/15 17:24:00','DD/MM/RR HH24:MI:SSXFF'), NULL);