CREATE DATABASE LINK CB.DBL CONNECT TO CB IDENTIFIED BY CB USING 'CB';


CREATE OR REPLACE TRIGGER COPIECOTESAVIS
BEFORE INSERT OR UPDATE ON EVALUATION
FOR EACH ROW
BEGIN
	DBMS_OUTPUT.PUT_LINE('DECLENCHEUR CBB');
	DBMS_OUTPUT.PUT_LINE('Token cbb 1 : ' || :NEW.TOKEN);
	:NEW.TOKEN := 'OK';
	DBMS_OUTPUT.PUT_LINE('Token cbb 2 : ' || :NEW.TOKEN);

		IF (INSERTING) THEN
			DBMS_OUTPUT.PUT_LINE('insert cbb');
			DBMS_OUTPUT.PUT_LINE('Token cbb 3 : ' || :NEW.TOKEN);
			INSERT INTO EVALUATION@CB.DBL (IDFILM, LOGIN, COTE, AVIS, DATEEVAL, TOKEN)
			VALUES (:NEW.IDFILM, :NEW.LOGIN, :NEW.COTE, :NEW.AVIS, :NEW.DATEEVAL, :NEW.TOKEN);
			DBMS_OUTPUT.PUT_LINE('Token cbb 4 : ' || :NEW.TOKEN);
		END IF;

		IF (UPDATING) THEN
			UPDATE EVALUATION@CB.DBL
			SET	COTE = :NEW.COTE,
				AVIS = :NEW.AVIS,
				DATEEVAL = :NEW.DATEEVAL,
				TOKEN = :NEW.TOKEN
			WHERE	IDFILM = :NEW.IDFILM AND LOGIN = :NEW.LOGIN;
		END IF;

EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('except cbb');
		DBMS_OUTPUT.PUT_LINE('Token cbb 5 : ' || :NEW.TOKEN);
		IF SQLCODE = -02291 THEN :NEW.TOKEN := 'KO';
		DBMS_OUTPUT.PUT_LINE('Token cbb 6 : ' || :NEW.TOKEN);
		ELSE RAISE;
		END IF;
END;
/


CREATE OR REPLACE TRIGGER COPIECOTESAVIS
BEFORE INSERT OR UPDATE ON EVALUATION
FOR EACH ROW
BEGIN
	DBMS_OUTPUT.PUT_LINE('DECLENCHEUR CBB');
END;
/