CREATE DATABASE LINK CB.DBL CONNECT TO CB IDENTIFIED BY CB USING 'CB';


CREATE OR REPLACE TRIGGER COPIECOTESAVIS
BEFORE INSERT ON EVALUATION
FOR EACH ROW
BEGIN
	IF :NEW.TOKEN IS NULL THEN :NEW.TOKEN := 'TRANSFERT';
		INSERT INTO EVALUATION@CB.DBL VALUES (IDFILM = :NEW.IDFILM, LOGIN = :NEW.LOGIN, COTE = :NEW.COTE, AVIS = :NEW.AVIS, DATEEVAL = :NEW.DATEEVAL);

	END IF;

	:NEW.TOKEN := NULL;
END;
/
