-- FINK Jérôme et SEEL Océane 
-- CreaCBLight

DROP TRIGGER COPIECOTESAVIS;
DROP TABLE EVALUATION;
DROP TABLE UTILISATEUR;


CREATE TABLE UTILISATEUR
(
	LOGIN		VARCHAR2(10) CONSTRAINT PK_UTILISATEUR_LOGIN PRIMARY KEY,
	PASSWORD	VARCHAR2(10)
);


CREATE TABLE EVALUATION
(
	IDFILM		NUMBER(10),
	LOGIN		VARCHAR2(10) CONSTRAINT REF_UTILISATEUR_LOGIN REFERENCES UTILISATEUR (LOGIN),
	COTE		NUMBER(2),
	AVIS		VARCHAR2(1000),
	DATEEVAL	DATE CONSTRAINT CK_DATEEVAL_NOTNULL CHECK (DATEEVAL IS NOT NULL),
	TOKEN		VARCHAR2(10) DEFAULT NULL,
	CONSTRAINT PK_EVALUATION_IFILM_LOGIN  PRIMARY KEY (IDFILM, LOGIN),
	CONSTRAINT CK_COTEAVIS_NOTNULL CHECK ((COTE IS NOT NULL AND AVIS IS NULL) OR (COTE IS NULL AND AVIS IS NOT NULL) OR (COTE IS NOT NULL AND AVIS IS NOT NULL))
);



-- INSERTION DES USERS
BEGIN
	INSERT INTO UTILISATEUR (LOGIN, PASSWORD) VALUES ('JEROME', 'FINK');
	INSERT INTO UTILISATEUR (LOGIN, PASSWORD) VALUES ('OCEANE', 'SEEL');
	INSERT INTO UTILISATEUR (LOGIN, PASSWORD) VALUES ('AAA', 'AAA');
	INSERT INTO UTILISATEUR (LOGIN, PASSWORD) VALUES ('BBB', 'BBB');
	INSERT INTO UTILISATEUR (LOGIN, PASSWORD) VALUES ('CCC', 'CCC');


	-- INSERTION DES EVALUATION

	INSERT INTO EVALUATION (IDFILM, LOGIN, COTE, AVIS, DATEEVAL) VALUES (1, 'JEROME', 5, NULL, to_timestamp('23/09/15 17:24:00','DD/MM/RR HH24:MI:SSXFF'));
	INSERT INTO EVALUATION (IDFILM, LOGIN, COTE, AVIS, DATEEVAL) VALUES (2, 'OCEANE', NULL, 'Film génial', to_timestamp('22/09/15 15:20:00','DD/MM/RR HH24:MI:SSXFF'));
	INSERT INTO EVALUATION (IDFILM, LOGIN, COTE, AVIS, DATEEVAL) VALUES (3, 'AAA', 7, NULL, to_timestamp('21/09/15 18:04:00','DD/MM/RR HH24:MI:SSXFF'));
	INSERT INTO EVALUATION (IDFILM, LOGIN, COTE, AVIS, DATEEVAL) VALUES (4, 'JEROME', 1, 'J''ai détesté ce film', to_timestamp('22/09/15 09:53:00','DD/MM/RR HH24:MI:SSXFF'));
	INSERT INTO EVALUATION (IDFILM, LOGIN, COTE, AVIS, DATEEVAL) VALUES (5, 'OCEANE', 10, NULL, to_timestamp('23/09/15 13:13:00','DD/MM/RR HH24:MI:SSXFF'));

	COMMIT;
END;
