-- FINK Jérôme et SEEL Océane 
-- CreaCBLight


DROP TABLE UTILISATEUR;
DROP TABLE EVALUATION;


CREATE TABLE UTILISATEUR
(
	LOGIN		VARCHAR2(10) CONSTRAINT PK_UTILISATEUR_LOGIN PRIMARY KEY,
	PASSWORD	VARCHAR2(10)
);


CREATE TABLE EVALUATION
(
	IDFILM		NUMBER(10),
	LOGIN		VARCHAR2(10) CONSTRAINT REF_EVALUATION_LOGIN_IN_UTILISATEUR REFERENCES UTILISATEUR (LOGIN),
	COTE		NUMBER(2),
	AVIS		NUMBER(1000),
	DATEEVAL	DATE CONSTRAINT CK_DATEEVAL_NOTNULL CHECK (DATEEVAL IS NOT NULL),
	CONSTRAINT PK_EVALUATION_IFILM_LOGIN  PRIMARY KEY (IDFILM, LOGIN),
	CONSTRAINT CK_COTEAVIS_NOTNULL CHECK ((COTE NOT NULL AND AVIS NULL) OR (COTE NULL AND AVIS NOT NULL) OR (COTE NOT NULL AND AVIS NOT NULL))
);



-- INSERTION DES USERS

INSERT INTO UTILISATEUR (LOGIN, PASSWORD) VALUES ('JEROME', 'FINK');
INSERT INTO UTILISATEUR (LOGIN, PASSWORD) VALUES ('OCEANE', 'SEEL');
INSERT INTO UTILISATEUR (LOGIN, PASSWORD) VALUES ('AAA', 'AAA');
INSERT INTO UTILISATEUR (LOGIN, PASSWORD) VALUES ('BBB', 'BBB');
INSERT INTO UTILISATEUR (LOGIN, PASSWORD) VALUES ('CCC', 'CCC');


-- INSERTION DES EVALUATION

INSERT INTO EVALUATION (IDFILM, LOGIN, COTE, AVIS, DATEEVAL) VALUES (NULL, 'JEROME', 5, NULL, to_timestamp('23/09/15','DD/MM/RR HH24:MI:SSXFF'));
INSERT INTO EVALUATION (IDFILM, LOGIN, COTE, AVIS, DATEEVAL) VALUES (NULL, 'OCEANE', NULL, 'Film génial', to_timestamp('22/09/15','DD/MM/RR HH24:MI:SSXFF'));
INSERT INTO EVALUATION (IDFILM, LOGIN, COTE, AVIS, DATEEVAL) VALUES (NULL, 'AAA', 7, NULL, to_timestamp('21/09/15','DD/MM/RR HH24:MI:SSXFF'));
INSERT INTO EVALUATION (IDFILM, LOGIN, COTE, AVIS, DATEEVAL) VALUES (NULL, 'JEROME', 1, 'J''ai détesté ce film', to_timestamp('22/09/15','DD/MM/RR HH24:MI:SSXFF'));
INSERT INTO EVALUATION (IDFILM, LOGIN, COTE, AVIS, DATEEVAL) VALUES (NULL, 'OCEANE', 10, NULL, to_timestamp('23/09/15','DD/MM/RR HH24:MI:SSXFF'));
