
ALTER SESSION SET PLSCOPE_SETTINGS = "IDENTIFIERS:NONE";

CREATE SEQUENCE SEQ_LOG;

CREATE TABLE LOG_TABLE
(
	ID 				NUMBER CONSTRAINT PK_LOG_TABLE PRIMARY KEY,
	EVENTTIME		TIMESTAMP,
	DESCRIPTION		VARCHAR2(4000),
	LOCALISATION	VARCHAR2(100)
);

COMMIT;

CREATE OR REPLACE PROCEDURE LogEvent(Emplacement IN LOG_TABLE.LOCALISATION%TYPE, Message IN LOG_TABLE.DESCRIPTION%TYPE)
AS
	PRAGMA AUTONOMOUS_TRANSACTION;

BEGIN

	INSERT INTO LOG_TABLE (EVENTTIME, DESCRIPTION, LOCALISATION) VALUES (CURRENT_TIMESTAMP, Message, Emplacement);

	COMMIT;

EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN RAISE_APPLICATION_ERROR (-20001, 'Impossible d''ecrire l''entree dans la table log'); ROLLBACK;
	WHEN OTHERS THEN ROLLBACK; RAISE;
	
END;
/

CREATE OR REPLACE TRIGGER logID
BEFORE INSERT ON LOG_TABLE
FOR EACH ROW
BEGIN
	SELECT SEQ_LOG.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

COMMIT;
