BEGIN
	INSERT INTO UTILISATEUR (LOGIN, PASSWORD) VALUES ('OCE', 'OCE');
	INSERT INTO EVALUATION (IDFILM, LOGIN, COTE, AVIS, DATEEVAL) VALUES (10, 'OCE', 10, 'Au top', to_timestamp('05/10/15 17:24:00','DD/MM/RR HH24:MI:SSXFF'));
	INSERT INTO EVALUATION (IDFILM, LOGIN, COTE, AVIS, DATEEVAL) VALUES (20, 'OCE', 7, NULL, to_timestamp('06/10/15 15:20:00','DD/MM/RR HH24:MI:SSXFF'));
	UPDATE EVALUATION SET COTE = 8 WHERE IDFILM = 20 AND LOGIN = 'OCE';
	COMMIT;
END;
/

EXEC RESTORE;
