CREATE TABLE filmSchema OF XMLType
XMLTYPE STORE AS OBJECT RELATIONAL
XMLSCHEMA "http://cc/film.xsd"
ELEMENT "film"
VARRAY "XMLDATA"."LIST_GENRE"."GENRE"
	STORE AS TABLE genres_table ((PRIMARY KEY (NESTED_TABLE_ID, SYS_NC_ARRAY_INDEX$)))
VARRAY "XMLDATA"."LIST_PRODUCTEURS"."PRODUCTEUR"
	STORE AS TABLE producteurs_table ((PRIMARY KEY (NESTED_TABLE_ID, SYS_NC_ARRAY_INDEX$)))
VARRAY "XMLDATA"."LIST_PAYS"."PAYS"
	STORE AS TABLE pays_table ((PRIMARY KEY (NESTED_TABLE_ID, SYS_NC_ARRAY_INDEX$)))
VARRAY "XMLDATA"."LIST_ACTEURS"."ACTEUR"
	STORE AS TABLE acteurs_table ((PRIMARY KEY (NESTED_TABLE_ID, SYS_NC_ARRAY_INDEX$)))
VARRAY "XMLDATA"."LIST_REALISATEURS"."REALISATEUR"
	STORE AS TABLE realisateurs_table ((PRIMARY KEY (NESTED_TABLE_ID, SYS_NC_ARRAY_INDEX$)))
VARRAY "XMLDATA"."LIST_LANGUES"."LANGUE"
	STORE AS TABLE langues_table ((PRIMARY KEY (NESTED_TABLE_ID, SYS_NC_ARRAY_INDEX$)))
VARRAY "XMLDATA"."LIST_AVIS"."AVIS"
	STORE AS TABLE avis_table ((PRIMARY KEY (NESTED_TABLE_ID, SYS_NC_ARRAY_INDEX$)));

