CREATE TABLE filmSchema OF XMLType
XMLTYPE STORE AS OBJECT RELATIONAL
XMLSCHEMA 'http://cc/film.xsd'
ELEMENT 'film'
VARRAY "XMLDATA"."GENRES.GENRE"
	STORE AS TABLE genres_table ((PRIMARY KEY (NESTED_TABLE_ID, SYS_NC_ARRAY_INDEX$)))
VARRAY "XMLDATA"."PRODUCTEURS.PRODUCTEUR"
	STORE AS TABLE producteurs_table ((PRIMARY KEY (NESTED_TABLE_ID, SYS_NC_ARRAY_INDEX$)))
VARRAY "XMLDATA"."LISTPAYS.PAYS"
	STORE AS TABLE pays_table ((PRIMARY KEY (NESTED_TABLE_ID, SYS_NC_ARRAY_INDEX$)))
VARRAY "XMLDATA"."ACTEURS.ACTEUR"
	STORE AS TABLE acteurs_table ((PRIMARY KEY (NESTED_TABLE_ID, SYS_NC_ARRAY_INDEX$)))
VARRAY "XMLDATA"."REALISATEURS.REALISATEUR"
	STORE AS TABLE realisateurs_table ((PRIMARY KEY (NESTED_TABLE_ID, SYS_NC_ARRAY_INDEX$)))
VARRAY "XMLDATA"."LANGUES.LANGUE"
	STORE AS TABLE langues_table ((PRIMARY KEY (NESTED_TABLE_ID, SYS_NC_ARRAY_INDEX$)));
