CREATE OR REPLACE PROCEDURE RECEPTION_FILM(xml_film IN XMLTYPE)
AS
BEGIN

	INSERT INTO FILMSCHEMA
	VALUES(xml_film);


EXCEPTION
	WHEN OTHERS THEN LOGEVENT('procedure alimCC', 'ERREUR : ' ||SQLERRM); ROLLBACK;
END;

