CREATE OR REPLACE PROCEDURE RECEPTION_FILM
AS
	elemXML XMLTYPE;
BEGIN
	
	FOR elemXML IN (SELECT * FROM tmpXMLMovie@CB.DBL) LOOP
		BEGIN
			INSERT INTO FILMSCHEMA VALUES(elemXML);
		EXCEPTION
			WHEN OTHERS THEN RAISE;
		END;
	END LOOP;

	FOR elemXML IN (SELECT * FROM tmpXMLCopy@CB.DBL) LOOP
		BEGIN
			INSERT INTO FILMSCHEMA VALUES(elemXML);
		EXCEPTION
			WHEN dup_val_on_index THEN LOGEVENT('reception film', 'Doublon decopie');
			WHEN OTHERS THEN RAISE;
		END;
	END LOOP;

	DELETE FROM tmpXMLMovie@CB.DBL;
	DELETE FROM tmpXMLCopy@CB.DBL;

	COMMIT;

EXCEPTION
	WHEN OTHERS THEN LOGEVENT('procedure alimCC', 'ERREUR : ' ||SQLERRM); ROLLBACK;
END;

