CREATE OR REPLACE PROCEDURE RECEPTION_FILM(xml_film IN BINARY)
AS
BEGIN

	LOGEVENT('youpie', 'reçu');

EXCEPTION
	WHEN OTHERS THEN LOGEVENT('procedure alimCC', 'ERREUR : ' ||SQLERRM); ROLLBACK;
END;

