BEGIN

	DBMS_XMLSCHEMA.REGISTERSCHEMA(
	  SCHEMAURL => 'http://cc/film.xsd',
	  SCHEMADOC => BFILENAME('MOVIEDIRECTORY', 'Film.xsd'),
	  LOCAL => TRUE, GENTYPES => TRUE, GENTABLES => FALSE,
	  CSID => NLS_CHARSET_ID('AL32UTF8'));

	DBMS_XMLSCHEMA.REGISTERSCHEMA(
	  SCHEMAURL => 'http://cc/prograEntrante.xsd',
	  SCHEMADOC => BFILENAME('MOVIEDIRECTORY', 'Progra.xsd'),
	  LOCAL => TRUE, GENTYPES => TRUE, GENTABLES => FALSE,
	  CSID => NLS_CHARSET_ID('AL32UTF8'));

	DBMS_XMLSCHEMA.REGISTERSCHEMA(
	  SCHEMAURL => 'http://cc/copie.xsd',
	  SCHEMADOC => BFILENAME('MOVIEDIRECTORY', 'Copie.xsd'),
	  LOCAL => TRUE, GENTYPES => TRUE, GENTABLES => FALSE,
	  CSID => NLS_CHARSET_ID('AL32UTF8'));

	DBMS_XMLSCHEMA.REGISTERSCHEMA(
	  SCHEMAURL => 'http://cc/programmation.xsd',
	  SCHEMADOC => BFILENAME('MOVIEDIRECTORY', 'Programmation.xsd'),
	  LOCAL => TRUE, GENTYPES => TRUE, GENTABLES => FALSE,
	  CSID => NLS_CHARSET_ID('AL32UTF8'));
END;
/

COMMIT;
