BEGIN

	DBMS_XMLSCHEMA.REGISTERSCHEMA(
	  SCHEMAURL => 'http://cc/film.xsd',
	  SCHEMADOC => BFILENAME('MOVIEDIRECTORY', 'film.xsd'),
	  LOCAL => TRUE, GENTYPES => TRUE, GENTABLES => FALSE,
	  CSID => NLS_CHARSET_ID('AL32UTF8'));

	DBMS_XMLSCHEMA.REGISTERSCHEMA(
	  SCHEMAURL => 'http://cc/copie.xsd',
	  SCHEMADOC => BFILENAME('MOVIEDIRECTORY', 'copie.xsd'),
	  LOCAL => TRUE, GENTYPES => TRUE, GENTABLES => FALSE,
	  CSID => NLS_CHARSET_ID('AL32UTF8'));

	DBMS_XMLSCHEMA.REGISTERSCHEMA(
	  SCHEMAURL => 'http://cc/programmation.xsd',
	  SCHEMADOC => BFILENAME('MOVIEDIRECTORY', 'programmation.xsd'),
	  LOCAL => TRUE, GENTYPES => TRUE, GENTABLES => FALSE,
	  CSID => NLS_CHARSET_ID('AL32UTF8'));
END;
/

COMMIT;
