
DROP TABLE LOG_TABLE;

CREATE TABLE LOG_TABLE
(
	EVENTTIME		TIMESTAMP,
	DESCRIPTION		VARCHAR2(100),
	LOCALISATION	VARCHAR2(100),
	CONSTRAINT PK_LOG_TABLE  PRIMARY KEY (EVENTTIME, DESCRIPTION)
);

COMMIT;
/

CREATE OR REPLACE PROCEDURE LogEvent(Emplacement IN LOG_TABLE.LOCALISATION%TYPE, Message IN LOG_TABLE.DESCRIPTION%TYPE)
AS
	PRAGMA AUTONOMOUS_TRANSACTION;

BEGIN

	INSERT INTO LOG_TABLE (EVENTTIME, DESCRIPTION, LOCALISATION) VALUES (CURRENT_TIMESTAMP, Message, Emplacement);

	COMMIT;

EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN RAISE_APPLICATION_ERROR (-20001, 'Impossible d''ecrire l''entree dans la table log'); ROLLBACK;
	WHEN OTHERS THEN ROLLBACK; RAISE;
	
END;
/

EXIT;
