BEGIN
	DBMS_SCHEDULER.CREATE_JOB
	(
		JOB_NAME => 'JOB_BACKUP',
		JOB_TYPE => 'STORED_PROCEDURE',
		JOB_ACTION => 'BACKUP',
		START_DATE => SYSTIMESTAMP,
		REPEAT_INTERVAL => 'FREQ=DAILY;BYHOUR=0;BYMINUTE=0;BYSECOND=0;',
		ENABLED => TRUE,
		COMMENTS => 'Backup des nouveaux utilisateurs et leurs évaluations du jour de leur création.'
	);

EXCEPTION
	WHEN OTHERS THEN LOGEVENT('CB : CREATE JOB_BACKUP', 'Job non créé => ' || SQLCODE || ' : ' || SQLERRM); RAISE;

END;
/

COMMIT;
