-- INSERTION DES USERS
BEGIN
	INSERT INTO UTILISATEUR (LOGIN, PASSWORD) VALUES ('JEROME', 'FINK');
	INSERT INTO UTILISATEUR (LOGIN, PASSWORD) VALUES ('OCEANE', 'SEEL');
	INSERT INTO UTILISATEUR (LOGIN, PASSWORD) VALUES ('AAA', 'AAA');
	INSERT INTO UTILISATEUR (LOGIN, PASSWORD) VALUES ('BBB', 'BBB');
	INSERT INTO UTILISATEUR (LOGIN, PASSWORD) VALUES ('CCC', 'CCC');


	-- INSERTION DES EVALUATION

	INSERT INTO EVALUATION (IDFILM, LOGIN, COTE, AVIS, DATEEVAL) VALUES (1, 'JEROME', 5, NULL, to_timestamp('23/09/15 17:24:00','DD/MM/RR HH24:MI:SSXFF'));
	INSERT INTO EVALUATION (IDFILM, LOGIN, COTE, AVIS, DATEEVAL) VALUES (2, 'OCEANE', NULL, 'Film génial', to_timestamp('22/09/15 15:20:00','DD/MM/RR HH24:MI:SSXFF'));
	INSERT INTO EVALUATION (IDFILM, LOGIN, COTE, AVIS, DATEEVAL) VALUES (3, 'AAA', 7, NULL, to_timestamp('21/09/15 18:04:00','DD/MM/RR HH24:MI:SSXFF'));
	INSERT INTO EVALUATION (IDFILM, LOGIN, COTE, AVIS, DATEEVAL) VALUES (4, 'JEROME', 1, 'J''ai détesté ce film', to_timestamp('22/09/15 09:53:00','DD/MM/RR HH24:MI:SSXFF'));
	INSERT INTO EVALUATION (IDFILM, LOGIN, COTE, AVIS, DATEEVAL) VALUES (5, 'OCEANE', 10, NULL, to_timestamp('23/09/15 13:13:00','DD/MM/RR HH24:MI:SSXFF'));

	COMMIT;
END;