-------------------
-- SPECIFICATION --
-------------------

CREATE OR REPLACE PACKAGE GESTIONCB
IS
	PROCEDURE BACKUP;
END;










----------
-- BODY --
----------

CREATE OR REPLACE PACKAGE BODY GESTIONCB
IS

	PROCEDURE BACKUP
	AS
	BEGIN

		-- UTILISATEURS
		INSERT INTO UTILISATEUR@CBB.DBL (LOGIN, PASSWORD, TOKEN) SELECT LOGIN, PASSWORD, 'OK' FROM UTILISATEUR WHERE TOKEN IS NULL;
		UPDATE UTILISATEUR SET TOKEN = 'OK' WHERE TOKEN IS NULL;

		-- EVALUATIONS
		INSERT INTO EVALUATION@CBB.DBL (IDFILM, LOGIN, COTE, AVIS, DATEEVAL, TOKEN) SELECT IDFILM, LOGIN, COTE, AVIS, DATEEVAL, 'OK' FROM EVALUATION WHERE TOKEN = 'KO';
		UPDATE EVALUATION SET TOKEN = 'OK' WHERE TOKEN = 'KO';

		COMMIT;

	END;

END;
