

-------------------
-- SPECIFICATION --
-------------------

CREATE OR REPLACE PACKAGE PACKAGERECHERCHE
IS
	PROCEDURE recherche(result OUT SYS_REFCURSOR);
	FUNCTION b_recherche RETURN SYS_REFCURSOR;
END;
/




----------
-- BODY --
----------

CREATE OR REPLACE PACKAGE BODY PACKAGERECHERCHE
IS

	PROCEDURE recherche(result OUT SYS_REFCURSOR)
	AS
	BEGIN
		OPEN result FOR SELECT id, Titre FROM FILM;
	EXCEPTION
		WHEN OTHERS THEN RAISE; --TO DO LOG
	END;

	FUNCTION b_recherche RETURN SYS_REFCURSOR
	AS
		result SYS_REFCURSOR;
	BEGIN
		OPEN result FOR SELECT id, Titre FROM FILM;
		RETURN result;
	EXCEPTION
		WHEN OTHERS THEN RAISE; --TO DO LOG
	END;

END;
/

EXIT;
