CREATE OR REPLACE TRIGGER TRUNCATEFILM
BEFORE INSERT OR UPDATE ON FILM
FOR EACH ROW
DECLARE
	
	tmp VARCHAR2(4000);

BEGIN
	IF LENGTH(:NEW.TITRE) > 58 THEN
		tmp := SUBSTR(:NEW.TITRE,0,58);
		LOGEVENT('FILM', 'TITRE ' || :NEW.TITRE || ' TRUNCATE AS ' || tmp);
		:NEW.TITRE := tmp;
	END IF;

	IF LENGTH(:NEW.TITRE_ORIGINAL) > 59 THEN
		tmp := SUBSTR(:NEW.TITRE_ORIGINAL,0,59);
		LOGEVENT('FILM', 'TITRE_ORIGINAL ' || :NEW.TITRE_ORIGINAL || ' TRUNCATE AS ' || tmp);
		:NEW.TITRE_ORIGINAL := tmp;
	END IF;

	IF LENGTH(:NEW.CERTIFICATION) > 5 THEN
		tmp := SUBSTR(:NEW.CERTIFICATION,0,5);
		LOGEVENT('FILM', 'CERTIFICATION ' || :NEW.CERTIFICATION || ' TRUNCATE AS ' || tmp);
		:NEW.CERTIFICATION := tmp;
	END IF;

	IF LENGTH(:NEW.TAGLINE) > 172 THEN
		tmp := SUBSTR(:NEW.TAGLINE,0,172);
		LOGEVENT('FILM', 'TAGLINE ' || :NEW.TAGLINE || ' TRUNCATE AS ' || tmp);
		:NEW.TAGLINE := tmp;
	END IF;

	IF LENGTH(:NEW.OVERVIEW) > 949 THEN
		tmp := SUBSTR(:NEW.OVERVIEW,0,949);
		LOGEVENT('FILM', 'OVERVIEW ' || :NEW.OVERVIEW || ' TRUNCATE AS ' || tmp);
		:NEW.OVERVIEW := tmp;
	END IF;

	IF LENGTH(:NEW.NOTE_MOYENNE) > 3 THEN
		IF :NEW.NOTE_MOYENNE > 10 THEN
			LOGEVENT('FILM', 'NOTE_MOYENNE = '|| :NEW.NOTE_MOYENNE||' VALUE TRUNCATE TO 10');
			:NEW.NOTE_MOYENNE := 10;
		ELSE
			LOGEVENT('FILM', 'NOTE_MOYENNE = '|| :NEW.NOTE_MOYENNE||' VALUE TRUNCATE TO ' || TRUNC(:NEW.NOTE_MOYENNE, 1));
			:NEW.NOTE_MOYENNE := TRUNC(:NEW.NOTE_MOYENNE, 1);
		END IF;
	END IF;


EXCEPTION
	WHEN OTHERS THEN RAISE;
END;
/

EXIT;