/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIapplicationFilm;

import com.sun.javafx.fxml.BeanAdapter;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import newBean.BeanBDAccess;

/**
 *
 * @author John
 */
public class ConnexionPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConnexionPanel
     */
    public ConnexionPanel() {
        initComponents();
        errorLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitreConnexion = new javax.swing.JLabel();
        loginTextField = new javax.swing.JTextField();
        LoginLabel = new javax.swing.JLabel();
        motDePasse = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        connexionButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        setForeground(new java.awt.Color(255, 0, 0));

        TitreConnexion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TitreConnexion.setText("RQS DataBase");

        LoginLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LoginLabel.setText("Login : ");

        motDePasse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        motDePasse.setText("Mot de passe : ");

        connexionButton.setText("Connexion");
        connexionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connexionButtonActionPerformed(evt);
            }
        });

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(connexionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(motDePasse)
                            .addComponent(LoginLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginTextField)
                            .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))))
                .addGap(270, 270, 270))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(TitreConnexion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(errorLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitreConnexion)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motDePasse)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(connexionButton)
                .addGap(18, 18, 18)
                .addComponent(errorLabel)
                .addContainerGap(218, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void connexionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connexionButtonActionPerformed
        errorLabel.setVisible(false);
        if(loginTextField.getText().isEmpty())
            return;
        
        ResultSet rs = null;
        GUI container = (GUI)SwingUtilities.getWindowAncestor(this); // on prend son grand pere
        BeanBDAccess conDB = container.getBeanbd();
       
        try {
            rs = conDB.selection("PASSWORD", "UTILISATEUR", "LOGIN = '" + loginTextField.getText() + "'");
        } catch (SQLException ex) {
            System.err.println("Erreur recuperation login");
            errorLabel.setText("Serveur indisponible");
            errorLabel.setVisible(true);
        }
        
        try {
            if(rs.next())
            {
                if(rs.getString("PASSWORD").equals(passwordField.getText()))
                {
                    container.setUser(loginTextField.getText());
                    container.changeLayout("accueil");
                    return;
                }
                
                errorLabel.setText("Mot de passe invalide");
                errorLabel.setVisible(true);
            }
            else
            {
                errorLabel.setText("Login invalide");
                errorLabel.setVisible(true);
            }
        } catch (SQLException ex) {
            errorLabel.setText("Serveur indisponible");
            errorLabel.setVisible(true);
        }
       
    }//GEN-LAST:event_connexionButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JLabel TitreConnexion;
    private javax.swing.JButton connexionButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JLabel motDePasse;
    private javax.swing.JPasswordField passwordField;
    // End of variables declaration//GEN-END:variables
}
