/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIapplicationFilm;

import java.awt.CardLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import newBean.BeanBDAccess;
import newBean.connexionException;

/**
 *
 * @author Jerome
 */
public class GUI extends javax.swing.JFrame {
    
    private BeanBDAccess connexionBD;
    private DefaultListModel listResult = new DefaultListModel();
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        rechercheResult.setListModel(listResult);
        connexionBD = new BeanBDAccess();
        try {
            connexionBD.connexionOracle("localhost", 1521, "CB", "CB", "XE");
        } catch (ClassNotFoundException ex) {
            System.err.println(ex);
        } catch (SQLException ex) {
            System.err.println(ex);
        } catch (connexionException ex) {
            System.err.println(ex);
        }
    }
    
    public void changeLayout(String nomCard)
    {
        CardLayout card = (CardLayout) this.getContentPane().getLayout();
        card.show(this.getContentPane(), nomCard);
    }
    
    public BeanBDAccess getBeanbd()
    {
        return connexionBD;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accueil = new GUIapplicationFilm.accueilPanel();
        formulaireRecherche = new GUIapplicationFilm.formulaireRecherche();
        rechercheResult = new GUIapplicationFilm.rechercheResult();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(accueil, "accueil");
        getContentPane().add(formulaireRecherche, "formulaireRecherche");
        getContentPane().add(rechercheResult, "result");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
    public void setResult(DefaultListModel res)
    {
        listResult = res;
    }
    
    public DefaultListModel getResult()
    {
        return listResult;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUIapplicationFilm.accueilPanel accueil;
    private GUIapplicationFilm.formulaireRecherche formulaireRecherche;
    private GUIapplicationFilm.rechercheResult rechercheResult;
    // End of variables declaration//GEN-END:variables
}
