/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIapplicationFilm;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author John
 */
public class noterDialog extends javax.swing.JDialog {
    
    private Connection conDB;
    private String curUser;
    private int curFilm;
    /**
     * Creates new form noterDialog
     */
    public noterDialog(java.awt.Frame parent, boolean modal, int idFilm, Connection c, String cu) {
        super(parent, modal);
        initComponents();
        erreurLabel.setVisible(false);
        conDB = c;
        curFilm = idFilm;
        curUser = cu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titreDialog = new javax.swing.JLabel();
        noteLabel = new javax.swing.JLabel();
        noteTextField = new javax.swing.JTextField();
        noteDixLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        commenterJtaxtArea = new javax.swing.JTextArea();
        evaluerButton = new javax.swing.JButton();
        erreurLabel = new javax.swing.JLabel();
        avisLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titreDialog.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titreDialog.setText("Noter film");

        noteLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noteLabel.setText("Note : ");

        noteDixLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noteDixLabel.setText("/10");

        commenterJtaxtArea.setColumns(20);
        commenterJtaxtArea.setRows(5);
        jScrollPane1.setViewportView(commenterJtaxtArea);

        evaluerButton.setText("Evaluer");
        evaluerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evaluerButtonActionPerformed(evt);
            }
        });

        erreurLabel.setForeground(new java.awt.Color(255, 0, 0));
        erreurLabel.setText("jLabel1");

        avisLabel.setText("Avis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(titreDialog))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(noteLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noteDixLabel))
                            .addComponent(erreurLabel)
                            .addComponent(avisLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(evaluerButton)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titreDialog)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noteLabel)
                    .addComponent(noteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noteDixLabel))
                .addGap(3, 3, 3)
                .addComponent(avisLabel)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erreurLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(evaluerButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void evaluerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evaluerButtonActionPerformed
        
        erreurLabel.setVisible(false);
        
        if(noteTextField.getText().isEmpty() && commenterJtaxtArea.getText().isEmpty())
        {
            erreurLabel.setText("Vous devez renseigner au moins une note ou un avis");
            erreurLabel.setVisible(true);
            return;
        }
        float note = -1;
        if(!noteTextField.getText().isEmpty())
        {
            try
            {
                note = Float.parseFloat(noteTextField.getText());
                
                if(note < 0 || 10 < note)
                {
                    erreurLabel.setText("La note doit être un nombre compris entre 0 et 10");
                    erreurLabel.setVisible(true);
                    return;
                }
            }
            catch(NumberFormatException ex)
            {
                erreurLabel.setText("La note doit être un nombre compris entre 0 et 10");
                erreurLabel.setVisible(true);
                return;
            }
        }
        
        CallableStatement cs = null;

        try {
            cs =  conDB.prepareCall("{call EVALFILM(?, ?, ?, ?)}");
            cs.setInt(1, curFilm);
            cs.setString(2, curUser);
            
            if(note != -1)
                cs.setFloat(3, note);
            else
                cs.setNull(3, OracleTypes.NUMBER);
            
            if(!commenterJtaxtArea.getText().isEmpty())
                cs.setString(4, commenterJtaxtArea.getText());
            else
                cs.setNull(4, OracleTypes.VARCHAR);
            
            cs.executeQuery();
            conDB.commit();
        } catch (SQLException ex) {
            System.err.println("erreur : " + ex);
            erreurLabel.setText("Echec d'envoi : reessayez plus tard.");
            erreurLabel.setVisible(true);
            
            try {
                conDB.rollback();
            } catch (SQLException ex1) {
                System.err.println("erreur : " + ex1);
            }
            return;
        }
        
        this.dispose();
    }//GEN-LAST:event_evaluerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisLabel;
    private javax.swing.JTextArea commenterJtaxtArea;
    private javax.swing.JLabel erreurLabel;
    private javax.swing.JButton evaluerButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel noteDixLabel;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JTextField noteTextField;
    private javax.swing.JLabel titreDialog;
    // End of variables declaration//GEN-END:variables
}
