-- SCRIPT D'INSERTION DANS MKT



BEGIN
	
	LOGEVENT('AlimMKT', 'Debut de l''alimentation');

	LOGEVENT('AlimMKT', 'insertion film');
	-- FILM
	FOR cpt IN 1..30 LOOP
		MERGE INTO FILM f USING (SELECT cpt id, ROUND(DBMS_RANDOM.VALUE(0, 10), 1) c FROM DUAL) v
		ON (f.IDFILM = v.id)
		WHEN MATCHED THEN UPDATE SET f.IDFILM = v.id, f.MOYCOTES = v.c
		WHEN NOT MATCHED THEN INSERT (IDFILM, MOYCOTES) VALUES(v.id, v.c);
	END LOOP;


	-- PAYS
	LOGEVENT('AlimMKT', 'insertion pays');

	BEGIN
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (1, 'Allemagne');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (2, 'Norvège');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (3, 'Australie');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (4, 'Autriche');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (5, 'Belgique');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (6, 'Brésil');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (7, 'Bulgarie');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (8, 'Canada');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (9, 'Chili');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (10, 'Chine');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (11, 'Chypre');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (12, 'Royaume-Unis');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (13, 'Croatie');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (14, 'Danemark');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (15, 'Espagne');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (16, 'Etats-Unis');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (17, 'Finlande');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (18, 'France');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (19, 'Grèce');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (20, 'Hongrie');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (21, 'Inde');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (22, 'Irlande');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (23, 'Italie');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (24, 'Japon');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (25, 'Pays-Bas');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (26, 'Nouvelle-Zélande');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (27, 'Malte');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (28, 'Suède');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (29, 'Mexique');
		INSERT INTO PAYS (IDPAYS, NOM) VALUES (30, 'Monaco');
	EXCEPTION
		WHEN OTHERS THEN LOGEVENT('AlimMKT', 'insertion des pays dejà effectuees');
	END;


	-- ACTEUR
	LOGEVENT('AlimMKT', 'insertion acteurs');

	BEGIN
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (1, 'Belgique');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (2, 'Etats-Unis');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (3, 'Espagne');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (4, 'France');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (5, 'Canada');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (6, 'Etats-Unis');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (7, 'Italie');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (8, 'Royaume-Unis');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (9, 'Etats-Unis');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (10, 'Royaume-Unis');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (11, 'Royaume-Unis');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (12, 'Canada');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (13, 'Etats-Unis');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (14, 'Royaume-Unis');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (15, 'Allemagne');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (16, 'Royaume-Unis');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (17, 'Etats-Unis');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (18, 'Italie');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (19, 'Royaume-Unis');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (20, 'Etats-Unis');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (21, 'Canada');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (22, 'Chine');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (23, 'France');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (24, 'Belgique');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (25, 'Etats-Unis');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (26, 'Canada');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (27, 'Royaume-Unis');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (28, 'Canada');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (29, 'Pologne');
		INSERT INTO ACTEUR (IDACTEUR, NATIONALITE) VALUES (30, 'Allemagne');
	EXCEPTION
		WHEN OTHERS THEN LOGEVENT('AlimMKT', 'insertion des acteurs dejà effectuees');
	END;

	-- GENRE
	LOGEVENT('AlimMKT', 'insertion genres');

	BEGIN
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (1, 'Action');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (2, 'Animation');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (3, 'Aventure');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (4, 'Biographique');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (5, 'Catastrophe');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (6, 'Comédie');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (7, 'Comédie dramatique');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (8, 'Comédie musicale');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (9, 'Comédie Policière');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (10, 'Comédie romantique');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (11, 'Court métrage');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (12, 'Dessin animé');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (13, 'Documentaire');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (14, 'Drame');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (15, 'Drame psychologique');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (16, 'Epouvante');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (17, 'Erotique');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (18, 'Espionnage');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (19, 'Fantastique');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (20, 'Guerre');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (21, 'Historique');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (22, 'Horreur');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (23, 'Manga');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (24, 'Mélodrame');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (25, 'Muet');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (26, 'Policier');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (27, 'Romance');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (28, 'Science fiction');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (29, 'Thriller');
		INSERT INTO GENRE (IDGENRE, NOM) VALUES (30, 'Western');
	EXCEPTION
		WHEN OTHERS THEN LOGEVENT('AlimMKT', 'insertion des genres dejà effectuees');
	END;


	-- LINK FILM ET PAYS/ACTEUR/GENRE
	LOGEVENT('AlimMKT', 'insertion pays/acteurs/genres');

	FOR cpt IN 1..30 LOOP
		MERGE INTO LINK_FILM_PAYS f USING (SELECT cpt id, FLOOR(DBMS_RANDOM.VALUE(1, 30)) c FROM DUAL) v
		ON (f.IDFILM = v.id)
		WHEN MATCHED THEN UPDATE SET f.IDFILM = v.id, f.IDPAYS = v.c
		WHEN NOT MATCHED THEN INSERT (IDFILM, IDPAYS) VALUES(v.id, v.c);

		MERGE INTO LINK_FILM_ACTEUR f USING (SELECT cpt id, FLOOR(DBMS_RANDOM.VALUE(1, 30)) c FROM DUAL) v
		ON (f.IDFILM = v.id)
		WHEN MATCHED THEN UPDATE SET f.IDFILM = v.id, f.IDACTEUR = v.c
		WHEN NOT MATCHED THEN INSERT (IDFILM, IDACTEUR) VALUES(v.id, v.c);

		MERGE INTO LINK_FILM_GENRE f USING (SELECT cpt id, FLOOR(DBMS_RANDOM.VALUE(1, 30)) c FROM DUAL) v
		ON (f.IDFILM = v.id)
		WHEN MATCHED THEN UPDATE SET f.IDFILM = v.id, f.IDGENRE = v.c
		WHEN NOT MATCHED THEN INSERT (IDFILM, IDGENRE) VALUES(v.id, v.c);
	END LOOP;


	-- COMPLEXE
	LOGEVENT('AlimMKT', 'insertion complexe');

	FOR cpt IN 1..30 LOOP
		MERGE INTO COMPLEXE f USING (SELECT 'CC'||cpt id FROM DUAL) v
		ON (f.IDCOMPLEXE = v.id)
		WHEN MATCHED THEN UPDATE SET f.IDCOMPLEXE = v.id
		WHEN NOT MATCHED THEN INSERT (IDCOMPLEXE) VALUES(v.id);
	END LOOP;


	-- SALLE
	LOGEVENT('AlimMKT', 'insertion salle');

	FOR cpt IN 1..30 LOOP
		INSERT INTO SALLE (IDSALLE, PLACESTOTALES, IDCOMPLEXE) VALUES (cpt, 300, 'CC'||cpt);

		MERGE INTO SALLE f USING (SELECT cpt id, 300 p, 'CC'||cpt s FROM DUAL) v
		ON (f.IDSALLE = v.id)
		WHEN MATCHED THEN UPDATE SET f.IDSALLE = v.id, f.PLACESTOTALES = v.p, f.IDCOMPLEXE = v.s
		WHEN NOT MATCHED THEN INSERT (IDSALLE, PLACESTOTALES, IDCOMPLEXE) VALUES(v.id, v.p, v.s);
	END LOOP;


	-- PROGRAMMATION
	LOGEVENT('AlimMKT', 'insertion programmation');

	BEGIN
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (1, to_timestamp('16/12/15 13:00:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 1);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (1, to_timestamp('16/12/15 18:30:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 1);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (1, to_timestamp('16/12/15 21:00:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 1);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (1, to_timestamp('17/12/15 13:00:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 1);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (1, to_timestamp('17/12/15 18:30:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 1);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (1, to_timestamp('17/12/15 21:00:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 1);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (1, to_timestamp('18/12/15 13:00:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 1);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (1, to_timestamp('18/12/15 18:30:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 1);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (1, to_timestamp('18/12/15 21:00:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 1);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (2, to_timestamp('16/12/15 13:00:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 2);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (2, to_timestamp('17/12/15 13:00:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 2);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (2, to_timestamp('18/12/15 13:00:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 2);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (2, to_timestamp('19/12/15 13:00:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 2);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (2, to_timestamp('20/12/15 13:00:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 2);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (2, to_timestamp('21/12/15 13:00:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 2);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (2, to_timestamp('22/12/15 13:00:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 2);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (3, to_timestamp('16/12/15 21:00:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 3);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (3, to_timestamp('17/12/15 21:00:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 3);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (3, to_timestamp('18/12/15 21:00:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 3);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (3, to_timestamp('19/12/15 21:00:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 3);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (3, to_timestamp('20/12/15 21:00:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 3);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (3, to_timestamp('21/12/15 21:00:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 3);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (3, to_timestamp('22/12/15 21:00:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 3);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (4, to_timestamp('16/12/15 18:30:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 4);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (4, to_timestamp('17/12/15 18:30:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 4);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (4, to_timestamp('18/12/15 18:30:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 4);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (4, to_timestamp('19/12/15 18:30:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 4);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (4, to_timestamp('20/12/15 18:30:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 4);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (4, to_timestamp('21/12/15 18:30:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 4);
		INSERT INTO PROGRAMMATION (IDFILM, DEBUT, PLACESVENDUES, IDSALLE) VALUES (4, to_timestamp('22/12/15 18:30:00','DD/MM/RR HH24:MI:SSXFF'), FLOOR(DBMS_RANDOM.VALUE(0, 300)), 4);
	EXCEPTION
		WHEN OTHERS THEN LOGEVENT('AlimMKT', 'insertion des programmations dejà effectuees');
	END;

	LOGEVENT('AlimMKT', 'Fin de l''alimentation');
	COMMIT;
EXCEPTION
	WHEN OTHERS THEN LOGEVENT('AlimMKT', 'Insertion ratee => ' || SQLCODE || ' : ' || SQLERRM); ROLLBACK;

END;
/