-- SCHEMA D'INTEGRATION





CREATE TABLE FILM
(
	IDFILM		NUMBER CONSTRAINT PK_FILM PRIMARY KEY,
	MOYCOTES	NUMBER
);


CREATE TABLE PAYS
(
	IDPAYS	NUMBER CONSTRAINT PK_PAYS PRIMARY KEY,
	NOM		VARCHAR2(35)
);


CREATE TABLE LINK_FILM_PAYS
(
	IDFILM	NUMBER CONSTRAINT REF_FILM_LFP REFERENCES FILM(IDFILM),
	IDPAYS	NUMBER CONSTRAINT REF_PAYS REFERENCES PAYS(IDPAYS),
	CONSTRAINT PK_LINK_FILM_PAYS PRIMARY KEY (IDFILM, IDPAYS)
);


CREATE TABLE ACTEUR
(
	IDACTEUR	NUMBER CONSTRAINT PK_ACTEUR PRIMARY KEY,
	NATIONALITE	VARCHAR2(35)
);


CREATE TABLE LINK_FILM_ACTEUR
(
	IDFILM		NUMBER CONSTRAINT REF_FILM_LFA REFERENCES FILM(IDFILM),
	IDACTEUR	NUMBER CONSTRAINT REF_ACTEUR REFERENCES ACTEUR(IDACTEUR),
	CONSTRAINT PK_LINK_FILM_ACTEUR PRIMARY KEY (IDFILM, IDACTEUR)
);


CREATE TABLE GENRE
(
	IDGENRE	NUMBER CONSTRAINT PK_GENRE PRIMARY KEY,
	NOM		VARCHAR2(20)
);


CREATE TABLE LINK_FILM_GENRE
(
	IDFILM	NUMBER CONSTRAINT REF_FILM_LFG REFERENCES FILM(IDFILM),
	IDGENRE	NUMBER CONSTRAINT REF_GENRE REFERENCES GENRE(IDGENRE),
	CONSTRAINT PK_LINK_FILM_GENRE PRIMARY KEY (IDFILM, IDGENRE)
);


CREATE TABLE COMPLEXE
(
	IDCOMPLEXE	VARCHAR2(100) CONSTRAINT PK_COMPLEXE PRIMARY KEY
);

CREATE TABLE SALLE
(
	IDSALLE			NUMBER CONSTRAINT PK_SALLE PRIMARY KEY,
	PLACESTOTALES	NUMBER,
	IDCOMPLEXE		VARCHAR2(100) CONSTRAINT REF_COMPLEXE REFERENCES COMPLEXE(IDCOMPLEXE)
);

CREATE TABLE PROGRAMMATION
(
	IDFILM			NUMBER CONSTRAINT REF_FILM_P REFERENCES FILM(IDFILM),
	DEBUT			TIMESTAMP,
	PLACESVENDUES	NUMBER,
	IDSALLE			NUMBER CONSTRAINT REF_SALLE REFERENCES SALLE(IDSALLE),
	CONSTRAINT PK_PROGRAMMATION PRIMARY KEY (IDFILM, DEBUT)
);

COMMIT;
