CREATE TABLE FILM
(
	IDFILM		NUMBER,
	MOYCOTES	NUMBER
);


CREATE TABLE PAYS
(
	IDPAYS	NUMBER,
	NOM		VARCHAR2
);


CREATE TABLE LINK_FILM_PAYS
(
	IDFILM	NUMBER CONSTRAINT REF_FILM REFERENCES FILM(IDFILM),
	IDPAYS	NUMBER CONSTRAINT REF_PAYS REFERENCES PAYS(IDPAYS)
);


CREATE TABLE ACTEUR
(
	IDACTEUR	NUMBER,
	NATIONALITE	VARCHAR2
);


CREATE TABLE LINK_FILM_ACTEUR
(
	IDFILM		NUMBER CONSTRAINT REF_FILM REFERENCES FILM(IDFILM),
	IDACTEUR	NUMBER CONSTRAINT REF_ACTEUR REFERENCES ACTEUR(IDACTEUR)
);


CREATE TABLE GENRE
(
	IDGENRE	NUMBER,
	NOM		VARCHAR2
);


CREATE TABLE LINK_FILM_GENRE
(
	IDFILM	NUMBER CONSTRAINT REF_FILM REFERENCES FILM(IDFILM),
	IDGENRE	NUMBER CONSTRAINT REF_GENRE REFERENCES GENRE(IDGENRE)
);


CREATE TABLE COMPLEXE
(
	COMPLEXE	VARCHAR2
);

CREATE TABLE SALLE
(
	IDSALLE			NUMBER,
	PLACESTOTALES	NUMBER,
	COMPLEXE		VARCHAR2 CONSTRAINT REF_COMPLEXE REFERENCES COMPLEXE(IDCOMPLEXE)
);

CREATE TABLE PROGRAMMATION
(
	IDFILM			NUMBER CONSTRAINT REF_FILM REFERENCES FILM(IDFILM),
	DEBUT			TIMESTAMP,
	PLACESVENDUES	NUMBER,
	IDSALLE			NUMBER CONSTRAINT REF_SALLE REFERENCES SALLE(IDSALLE)
);

-- CREATE TABLE NBJOURSPROJ
-- (
-- 	NBJOURSPROJ	NUMBER,
-- 	IDFILM		NUMBER CONSTRAINT REF_FILM REFERENCES FILM(IDFILM),
-- 	COMPLEXE	NUMBER CONSTRAINT REF_COMPLEXE REFERENCES COMPLEXE(IDCOMPLEXE)
-- );
