-------------------
-- SPECIFICATION --
-------------------

CREATE OR REPLACE PACKAGE ALIMDW
IS
	PROCEDURE LOAD;
END;
/





----------
-- BODY --
----------

CREATE OR REPLACE PACKAGE BODY ALIMDW
IS
	-- Procédure alimentant tout le schéma (idéal pour un job)
	PROCEDURE LOAD
	AS 
	BEGIN
		ALIMDW.LOAD_DIMENSIONS;
		--ALIMDW.LOAD_FAITS;
	EXCEPTION
		WHEN OTHERS THEN LOGEVENT('ALIMDW - PROCEDURE LOAD', 'ERREUR : ' || SQLERRM); ROLLBACK;
	END;


	-- Procédure alimentant toutes les dimensions
	PROCEDURE LOAD_DIMENSIONS
	AS

	BEGIN

		MERGE INTO DIM_GENRE T1 USING (SELECT NOM FROM GENRE) T2 ON (T1.GENRE = T2.NOM)
		WHEN NOT MATCHED THEN INSERT (T1.GENRE) VALUES (T2.NOM);

		MERGE INTO DIM_SALLE T1 USING (SELECT IDSALLE FROM SALLE) T2 ON (T1.SALLE = T2.IDSALLE)
		WHEN NOT MATCHED THEN INSERT (T1.SALLE) VALUES (T2.IDSALLE);

		MERGE INTO DIM_COMPLEXE T1 USING (SELECT IDCOMPLEXE FROM COMPLEXE) T2 ON (T1.COMPLEXE = T2.IDCOMPLEXE)
		WHEN NOT MATCHED THEN INSERT (T1.COMPLEXE) VALUES (T2.IDCOMPLEXE);

		MERGE INTO DIM_PAYS T1 USING (SELECT NOM FROM PAYS) T2 ON (T1.PAYS = T2.NOM)
		WHEN NOT MATCHED THEN INSERT (T1.PAYS) VALUES (T2.NOM);

		MERGE INTO DIM_PAYS T1 USING (SELECT NATIONALITE FOM ACTEUR) T2 ON (T1.PAYS = T2.NATIONALITE)
		WHEN NOT MATCHED THEN INSERT (T1.PAYS) VALUES (T2.NATIONALITE);

		MERGE INTO DIM_FILM T1 USING (SELECT IDFILM  FROM FILM) T2 ON (T1.FILM = T2.IDFILM)
		WHEN NOT MATCHED THEN INSERT (T1.FILM) VALUES (T2.IDFILM);

		MERGE INTO DIM_PERIODE T1 USING (SELECT IDCOMPLEXE  FROM COMPLEXE) T2 ON (T1.IDCOMPLEXE = T2.IDCOMPLEXE)
		WHEN NOT MATCHED THEN INSERT (T1.PERIODE) VALUES (T2.IDCOMPLEXE);

		MERGE INTO DIM_JOUR T1 USING (SELECT EXTRACT(DAY FROM DEBUT) FROM PROGRAMMATION) T2 ON (T1.JOUR = )
		WHEN NOT MATCHED THEN INSERT (T1.JOUR) VALUES (T2.IDCOMPLEXE);

		MERGE INTO DIM_SEMAINE T1 USING (SELECT EXTRACT(DAY FROM DEBUT) FROM PROGRAMMATION) T2 ON (T1.SEMAINE = T2.NOM)
		WHEN NOT MATCHED THEN INSERT (T1.SEMAINE) VALUES (T2.NOM);

		MERGE INTO DIM_MOIS T1 USING (SELECT EXTRACT(MONTH FROM DEBUT) FROM PROGRAMMATION) T2 ON (T1.MOIS = T2.NATIONALITE)
		WHEN NOT MATCHED THEN INSERT (T1.MOIS) VALUES (TO_DATE('01/'||EXTRACT(MONTH FROM T2.DEBUT)||'/'||EXTRACT(YEAR FROM T2.DEBUT), 'dd/mm/yyyy'));

		MERGE INTO DIM_ANNEE T1 USING (SELECT EXTRACT(YEAR FROM DEBUT) FROM PROGRAMMATION) T2 ON (T1.ANNEE = T2.IDFILM)
		WHEN NOT MATCHED THEN INSERT (T1.ANNEE) VALUES (T2.IDFILM);

		COMMIT;

	EXCEPTION
		WHEN OTHERS THEN LOGEVENT('ALIMDW - PROCEDURE LOAD_DIMENSIONS', 'ERREUR : ' || SQLERRM); ROLLBACK;
	END;


	-- Procédure alimentant tous les faits
	--PROCEDURE LOAD_FAITS
	--AS

	--BEGIN

	--EXCEPTION
		--WHEN OTHERS THEN LOGEVENT('ALIMDW - PROCEDURE LOAD_FAITS', 'ERREUR : ' || SQLERRM); ROLLBACK;
	--END;
END;
/
