-- SCHEMA DE DIFFUSION





-- DIMENSION GENRE

CREATE TABLE DIM_GENRE
(
	GENRE VARCHAR2(20) CONSTRAINT PK_DIM_GENRE PRIMARY KEY
);



-- DIMENSION GEOGRAPHIQUE

CREATE TABLE DIM_SALLE
(
	SALLE NUMBER CONSTRAINT PK_DIM_SALLE PRIMARY KEY
);

CREATE TABLE DIM_COMPLEXE
(
	COMPLEXE VARCHAR2(100) CONSTRAINT PK_DIM_COMPLEXE PRIMARY KEY
);

CREATE TABLE DIM_PAYS
(
	PAYS VARCHAR2(35) CONSTRAINT PK_DIM_PAYS PRIMARY KEY
);



-- DIMENSION FILM

CREATE TABLE DIM_FILM
(
	FILM NUMBER CONSTRAINT PK_DIM_FILM PRIMARY KEY
);



-- DIMENSION TEMPORELLE

CREATE TABLE DIM_PERIODE
(
	PERIODE VARCHAR2(10) CONSTRAINT PK_DIM_PERIODE PRIMARY KEY
);

CREATE TABLE DIM_JOUR
(
	JOUR NUMBER CONSTRAINT PK_DIM_JOUR PRIMARY KEY
);

CREATE TABLE DIM_SEMAINE
(
	SEMAINE NUMBER CONSTRAINT PK_DIM_SEMAINE PRIMARY KEY
);

CREATE TABLE DIM_MOIS
(
	MOIS DATE CONSTRAINT PK_DIM_MOIS PRIMARY KEY
);

CREATE TABLE DIM_ANNEE
(
	ANNEE DATE CONSTRAINT PK_DIM_ANNEE PRIMARY KEY
);





-- FAIT 1A : La nationalité de l'acteur influe-t-elle sur le nombre de jours qu'un film reste à l'affiche ?

CREATE TABLE FAIT_NBJOURSPROJ
(
	NATIONALITE		VARCHAR2(35) CONSTRAINT REF_DIM_PAYS_NJP REFERENCES DIM_PAYS(PAYS),
	NBJOURSPROJ 	NUMBER
);


-- FAIT 1B : La nationalité de l'acteur influe-t-elle sur la moyenne des notes que donnent les utilisateurs à un film ?

CREATE TABLE FAIT_MOYNOTES
(
	NATIONALITE	VARCHAR2(35) CONSTRAINT REF_DIM_PAYS_MN REFERENCES DIM_PAYS(PAYS),
	MOYNOTES 	NUMBER
);


-- FAIT 2 : Quelles sont les popularités des films projetés tenant compte ou non des genres du film, de la salle, de la période de la journée (matin, après-midi, soir) ou encore du jour, de la semaine ou du mois de la projection ?

CREATE TABLE FAIT_POPULARITE
(
	GENRE		VARCHAR2(20) CONSTRAINT REF_DIM_GENRE_PO REFERENCES DIM_GENRE(GENRE),
	SALLE		NUMBER CONSTRAINT REF_DIM_SALLE_PO REFERENCES DIM_SALLE(SALLE),
	PERIODE		VARCHAR2(10) CONSTRAINT REF_DIM_PERIODE_PO REFERENCES DIM_PERIODE(PERIODE),
	JOUR		NUMBER CONSTRAINT REF_DIM_JOUR_PO REFERENCES DIM_JOUR(JOUR),
	SEMAINE		NUMBER CONSTRAINT REF_DIM_SEMAINE_PO REFERENCES DIM_SEMAINE(SEMAINE),
	MOIS		DATE CONSTRAINT REF_DIM_MOIS_PO REFERENCES DIM_MOIS(MOIS),
	POPULARITE	NUMBER
);


-- FAIT 3 : La cote d'un film est-elle liée au nombre de jours qu'un film est projeté ?

CREATE TABLE FAIT_COTE
(
	FILM			NUMBER CONSTRAINT REF_DIM_FILM_C REFERENCES DIM_FILM(FILM),
	NBJOURSPROJ		NUMBER,
	COTE 			NUMBER
);


-- FAIT 4 : Quelles sont les proportions de places vendues par salle ou complexe, par mois ou par année ?

CREATE TABLE FAIT_PROPORTION
(
	SALLE		NUMBER CONSTRAINT REF_DIM_SALLE_PR REFERENCES DIM_SALLE(SALLE),
	COMPLEXE	VARCHAR2(100) CONSTRAINT REF_DIM_COMPLEXE_PR REFERENCES DIM_COMPLEXE(COMPLEXE),
	MOIS		DATE CONSTRAINT REF_DIM_MOIS_PR REFERENCES DIM_MOIS(MOIS),
	ANNEE		DATE CONSTRAINT REF_DIM_ANNEE_PR REFERENCES DIM_ANNEE(ANNEE),
	PROPORTION	NUMBER
);


-- FAIT 5 : Quel est le turn over des copies au sein des installations tenant compte du genre des films, de la semaine ou de l'année et du pays de production du film ?

CREATE TABLE FAIT_TURNOVER
(
	GENRE		VARCHAR2(20) CONSTRAINT REF_DIM_GENRE_T REFERENCES DIM_GENRE(GENRE),
	SEMAINE		NUMBER CONSTRAINT REF_DIM_SEMAINE_T REFERENCES DIM_SEMAINE(SEMAINE),
	ANNEE		DATE CONSTRAINT REF_DIM_ANNEE_T REFERENCES DIM_ANNEE(ANNEE),
	PAYS		VARCHAR2(35) CONSTRAINT REF_DIM_PAYS_T REFERENCES DIM_PAYS(PAYS),
	TURNOVER	NUMBER
);



-- DB LINK POUR ALLER LIRE SUR MKT
CREATE DATABASE LINK MKT.DBL CONNECT TO MKT IDENTIFIED BY MKT USING 'MKT';
