DROP TABLE FAIT_NBJOURSPROJ;
DROP TABLE FAIT_MOYNOTES;
DROP TABLE FAIT_POPULARITE;
DROP TABLE FAIT_COTE;
DROP TABLE FAIT_PROPORTION;
DROP TABLE FAIT_TURNOVER;

DROP TABLE DIM_GENRE;
DROP TABLE DIM_SALLE;
DROP TABLE DIM_COMPLEXE;
DROP TABLE DIM_PAYS;
DROP TABLE DIM_FILM;
DROP TABLE DIM_PERIODE;
DROP TABLE DIM_JOUR;
DROP TABLE DIM_SEMAINE;
DROP TABLE DIM_MOIS;
DROP TABLE DIM_ANNEE;
