-------------------
-- SPECIFICATION --
-------------------

CREATE OR REPLACE PACKAGE ALIMDW
IS
	PROCEDURE LOAD;
END;
/





----------
-- BODY --
----------

CREATE OR REPLACE PACKAGE BODY ALIMDW
IS
	-- Procédure alimentant toutes les dimensions
	PROCEDURE LOAD_DIMENSIONS
	AS
		Heure NUMBER;
	BEGIN

		MERGE INTO DIM_GENRE T1 USING (SELECT NOM FROM GENRE@MKT.DBL) T2 ON (T1.GENRE = T2.NOM)
		WHEN NOT MATCHED THEN INSERT (T1.GENRE) VALUES (T2.NOM);

		MERGE INTO DIM_SALLE T1 USING (SELECT IDSALLE FROM SALLE@MKT.DBL) T2 ON (T1.SALLE = T2.IDSALLE)
		WHEN NOT MATCHED THEN INSERT (T1.SALLE) VALUES (T2.IDSALLE);

		MERGE INTO DIM_COMPLEXE T1 USING (SELECT IDCOMPLEXE FROM COMPLEXE@MKT.DBL) T2 ON (T1.COMPLEXE = T2.IDCOMPLEXE)
		WHEN NOT MATCHED THEN INSERT (T1.COMPLEXE) VALUES (T2.IDCOMPLEXE);

		MERGE INTO DIM_PAYS T1 USING (SELECT NOM FROM PAYS@MKT.DBL) T2 ON (T1.PAYS = T2.NOM)
		WHEN NOT MATCHED THEN INSERT (T1.PAYS) VALUES (T2.NOM);

		MERGE INTO DIM_PAYS T1 USING (SELECT NATIONALITE FROM ACTEUR@MKT.DBL) T2 ON (T1.PAYS = T2.NATIONALITE)
		WHEN NOT MATCHED THEN INSERT (T1.PAYS) VALUES (T2.NATIONALITE);

		MERGE INTO DIM_FILM T1 USING (SELECT IDFILM  FROM FILM@MKT.DBL) T2 ON (T1.FILM = T2.IDFILM)
		WHEN NOT MATCHED THEN INSERT (T1.FILM) VALUES (T2.IDFILM);

		SELECT EXTRACT (HOUR FROM DEBUT) INTO Heure FROM PROGRAMMATION@MKT.DBL;
		IF Heure < 12 THEN
			MERGE INTO DIM_PERIODE T1 USING (SELECT 'MATIN' FROM DUAL) T2 ON (T1.PERIODE = Heure)
			WHEN NOT MATCHED THEN INSERT (T1.PERIODE) VALUES ('MATIN');
		ELSIF Heure > 18 THEN
			MERGE INTO DIM_PERIODE T1 USING (SELECT 'SOIR' FROM DUAL) T2 ON (T1.PERIODE = Heure)
			WHEN NOT MATCHED THEN INSERT (T1.PERIODE) VALUES ('SOIR');
		ELSE
			MERGE INTO DIM_PERIODE T1 USING (SELECT 'APRES-MIDI' FROM DUAL) T2 ON (T1.PERIODE = Heure)
			WHEN NOT MATCHED THEN INSERT (T1.PERIODE) VALUES ('APRES-MIDI');
		END IF;

		MERGE INTO DIM_JOUR T1 USING (SELECT EXTRACT(DAY FROM DEBUT) d FROM PROGRAMMATION@MKT.DBL) T2 ON (T1.JOUR = T2.d)
		WHEN NOT MATCHED THEN INSERT (T1.JOUR) VALUES (T2.d);

		MERGE INTO DIM_SEMAINE T1 USING (SELECT TO_CHAR(DEBUT,'IW') d FROM PROGRAMMATION@MKT.DBL) T2 ON (T1.SEMAINE = T2.d)
		WHEN NOT MATCHED THEN INSERT (T1.SEMAINE) VALUES (T2.d);

		MERGE INTO DIM_MOIS T1 USING (SELECT (TO_DATE('01/'||EXTRACT(MONTH FROM DEBUT)||'/'||EXTRACT(YEAR FROM DEBUT), 'dd/mm/yyyy')) d FROM PROGRAMMATION@MKT.DBL) T2 ON (T1.MOIS = T2.d)
		WHEN NOT MATCHED THEN INSERT (T1.MOIS) VALUES (T2.d);

		MERGE INTO DIM_ANNEE T1 USING (SELECT (TO_DATE('01/01'||EXTRACT(YEAR FROM DEBUT), 'dd/mm/yyyy')) d FROM PROGRAMMATION@MKT.DBL) T2 ON (T1.ANNEE = T2.d)
		WHEN NOT MATCHED THEN INSERT (T1.ANNEE) VALUES (T2.d);

		COMMIT;

	EXCEPTION
		WHEN OTHERS THEN LOGEVENT('ALIMDW - PROCEDURE LOAD_DIMENSIONS', 'ERREUR : ' || SQLERRM); ROLLBACK;
	END;


	-- Procédure alimentant tous les faits
	--PROCEDURE LOAD_FAITS
	--AS

	--BEGIN

	--EXCEPTION
		--WHEN OTHERS THEN LOGEVENT('ALIMDW - PROCEDURE LOAD_FAITS', 'ERREUR : ' || SQLERRM); ROLLBACK;
	--END;


	-- Procédure alimentant tout le schéma (idéal pour un job)
	PROCEDURE LOAD
	AS 
	BEGIN
		ALIMDW.LOAD_DIMENSIONS;
		--ALIMDW.LOAD_FAITS;
	EXCEPTION
		WHEN OTHERS THEN LOGEVENT('ALIMDW - PROCEDURE LOAD', 'ERREUR : ' || SQLERRM); ROLLBACK;
	END;
END;
/
